#!/usr/bin/env python3
"""
toml2cpp.py - Modern, lightweight TOML to C++ code generator using toml++ and tomllib.

Usage:
    python3 toml2cpp.py --toml=<input.default.toml> --hpp=<output.hpp> --cpp=<output.cpp> [--ns=<namespace>] [--cn=<class_name>]
"""

import sys
import os
import argparse

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        sys.exit("Error: Python 3.11+ (tomllib) or 'tomli' package is required.")


def get_cpp_type(val):
    if isinstance(val, bool):
        return "bool"
    elif isinstance(val, int):
        return "int64_t"
    elif isinstance(val, float):
        return "double"
    elif isinstance(val, str):
        return "std::string"
    elif isinstance(val, list):
        if not val:
            return "std::vector<std::string>" # default empty array fallback
        elem_type = get_cpp_type(val[0])
        return f"std::vector<{elem_type}>"
    else:
        return "std::string"


def format_cpp_literal(val):
    if isinstance(val, bool):
        return "true" if val else "false"
    elif isinstance(val, str):
        escaped = val.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    elif isinstance(val, list):
        elems = ", ".join(format_cpp_literal(e) for e in val)
        return f"{{{elems}}}"
    else:
        return str(val)


class ClassNode:
    def __init__(self, name):
        self.name = name
        self.members = {}     # name -> value
        self.subclasses = {}  # name -> ClassNode

    def parse_dict(self, d):
        for k, v in d.items():
            if isinstance(v, dict):
                sub = ClassNode(k)
                sub.parse_dict(v)
                self.subclasses[k] = sub
            else:
                self.members[k] = v


def generate_hpp(root, ns, class_name, hpp_path):
    lines = [
        "// Auto-generated by modern toml2cpp.py. DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <string>",
        "#include <vector>",
        "#include <cstdint>",
        "#include <memory>",
        "",
        f"namespace {ns} {{",
        ""
    ]

    def write_struct_decl(node, is_top=False):
        cname = class_name if is_top else node.name.capitalize()
        lines.append(f"class {cname} {{")
        lines.append("public:")
        
        # Subclasses
        for sub_name, sub_node in node.subclasses.items():
            write_struct_decl(sub_node, False)
            lines.append("")

        # Default constructor
        lines.append(f"    {cname}() = default;")

        # Parameterized constructor for static initialization
        params = []
        for mname, mval in node.members.items():
            t = get_cpp_type(mval)
            params.append(f"{t} const& {mname}")
        for sub_name, sub_node in node.subclasses.items():
            sub_cname = sub_node.name.capitalize()
            params.append(f"{sub_cname} const& {sub_name}")
        
        param_str = ", ".join(params)
        lines.append(f"    {cname}({param_str});")
        lines.append("")

        # Getters
        for mname, mval in node.members.items():
            t = get_cpp_type(mval)
            lines.append(f"    {t} const& get_{mname}() const {{ return m_{mname}; }}")
        for sub_name, sub_node in node.subclasses.items():
            sub_cname = sub_node.name.capitalize()
            lines.append(f"    {sub_cname} const& get_{sub_name}() const {{ return m_{sub_name}; }}")
        lines.append("")

        # Update from TOML node (forward decl for toml++ node view)
        lines.append("    // Internal runtime update helper")
        lines.append("    template <typename NodeView>")
        lines.append("    void update_from_toml(NodeView const& node);")
        lines.append("")

        if is_top:
            lines.append("    static " + cname + " const& get_compile_time_values();")
            lines.append("    static " + cname + " get_run_time_values();")
            lines.append("")

        lines.append("private:")
        for mname, mval in node.members.items():
            t = get_cpp_type(mval)
            lines.append(f"    {t} m_{mname};")
        for sub_name, sub_node in node.subclasses.items():
            sub_cname = sub_node.name.capitalize()
            lines.append(f"    {sub_cname} m_{sub_name};")
        
        lines.append(f"}}; // class {cname}")

    write_struct_decl(root, True)
    lines.append("")
    lines.append(f"}} // namespace {ns}")
    lines.append("")

    with open(hpp_path, "w") as f:
        f.write("\n".join(lines))


def generate_cpp(root, ns, class_name, hpp_filename, cpp_path, bare_toml_name):
    lines = [
        "// Auto-generated by modern toml2cpp.py. DO NOT EDIT.",
        f'#include "{ns}/{os.path.basename(hpp_filename)}"',
        "#include <toml++/toml.hpp>",
        "#include <filesystem>",
        "#include <iostream>",
        "",
        "// Override directory hook. Can be implemented by application code.",
        "// Default implementation returns current directory if not overridden.",
        "#if !defined(_MSC_VER)",
        "__attribute__((weak))",
        "#endif",
        "std::string get_toml_config_directory() {",
        '    return ".";',
        "}",
        "",
        f"namespace {ns} {{",
        ""
    ]

    def write_struct_impl(node, is_top=False, parent_qualifier=""):
        cname = class_name if is_top else node.name.capitalize()
        qualifier = f"{parent_qualifier}{cname}::"

        # Implement subclasses first
        for sub_name, sub_node in node.subclasses.items():
            write_struct_impl(sub_node, False, qualifier)

        # Constructor implementation
        params = []
        inits = []
        for mname, mval in node.members.items():
            t = get_cpp_type(mval)
            params.append(f"{t} const& {mname}")
            inits.append(f"m_{mname}({mname})")
        for sub_name, sub_node in node.subclasses.items():
            sub_cname = sub_node.name.capitalize()
            params.append(f"{sub_cname} const& {sub_name}")
            inits.append(f"m_{sub_name}({sub_name})")
        
        param_str = ", ".join(params)
        init_str = ", ".join(inits)
        if init_str:
            init_str = " : " + init_str
        lines.append(f"{qualifier}{cname}({param_str}){init_str} {{}}")
        lines.append("")

        # Template update_from_toml implementation
        lines.append(f"template <typename NodeView>")
        lines.append(f"void {qualifier}update_from_toml(NodeView const& node) {{")
        for mname, mval in node.members.items():
            t = get_cpp_type(mval)
            if isinstance(mval, list):
                lines.append(f'    if (auto arr = node["{mname}"].as_array()) {{')
                lines.append(f'        m_{mname}.clear();')
                elem_t = get_cpp_type(mval[0]) if mval else "std::string"
                lines.append(f'        for (auto&& elem : *arr) {{')
                lines.append(f'            if (auto val = elem.template value<{elem_t}>()) m_{mname}.push_back(*val);')
                lines.append(f'        }}')
                lines.append(f'    }}')
            else:
                lines.append(f'    if (auto val = node["{mname}"].template value<{t}>()) {{')
                lines.append(f'        m_{mname} = *val;')
                lines.append(f'    }}')
        for sub_name, sub_node in node.subclasses.items():
            lines.append(f'    m_{sub_name}.update_from_toml(node["{sub_name}"]);')
        lines.append("}")
        lines.append("")

    write_struct_impl(root, True, "")

    # Compile time defaults
    lines.append(f"{class_name} const& {class_name}::get_compile_time_values() {{")
    
    def format_constructor_call(node, is_top=False):
        cname = class_name if is_top else node.name.capitalize()
        args = []
        for mname, mval in node.members.items():
            args.append(format_cpp_literal(mval))
        for sub_name, sub_node in node.subclasses.items():
            args.append(format_constructor_call(sub_node, False))
        return f"{cname}(" + ", ".join(args) + ")"

    lines.append(f"    static {class_name} const default_settings = {format_constructor_call(root, True)};")
    lines.append("    return default_settings;")
    lines.append("}")
    lines.append("")

    # Run time override loader
    lines.append(f"{class_name} {class_name}::get_run_time_values() {{")
    lines.append(f"    {class_name} current = get_compile_time_values();")
    lines.append(f'    std::filesystem::path config_path = std::filesystem::path(get_toml_config_directory()) / "{bare_toml_name}.toml";')
    lines.append("    if (std::filesystem::exists(config_path)) {")
    lines.append("        try {")
    lines.append("            auto res = toml::parse_file(config_path.string());")
    lines.append("            current.update_from_toml(res);")
    lines.append("        } catch (const std::exception& e) {")
    lines.append('            std::cerr << "[toml2cpp] Warning: Failed to parse override config " << config_path << ": " << e.what() << "\\n";')
    lines.append("        }")
    lines.append("    }")
    lines.append("    return current;")
    lines.append("}")
    lines.append("")

    lines.append(f"}} // namespace {ns}")
    lines.append("")

    with open(cpp_path, "w") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description="TOML to C++ code generator")
    parser.add_argument("--toml", required=True, help="Input TOML default file")
    parser.add_argument("--hpp", required=True, help="Output HPP file")
    parser.add_argument("--cpp", required=True, help="Output CPP file")
    parser.add_argument("--ns", default="config", help="C++ namespace")
    parser.add_argument("--cn", default="", help="C++ top class name")
    
    args, unknown = parser.parse_known_args()

    if not args.cn:
        base = os.path.basename(args.toml)
        bare = base.split(".")[0]
        args.cn = "".join(w.capitalize() for w in bare.split("_"))

    bare_toml_name = os.path.basename(args.toml).split(".")[0]

    with open(args.toml, "rb") as f:
        toml_data = tomllib.load(f)

    root = ClassNode(args.cn)
    root.parse_dict(toml_data)

    os.makedirs(os.path.dirname(os.path.abspath(args.hpp)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(args.cpp)), exist_ok=True)

    generate_hpp(root, args.ns, args.cn, args.hpp)
    generate_cpp(root, args.ns, args.cn, args.hpp, args.cpp, bare_toml_name)
    print(f"Successfully generated {args.hpp} and {args.cpp} for class {args.ns}::{args.cn}")


if __name__ == "__main__":
    main()
